-- Databricks SQL script to load Parquet files as tables
-- Auto-generated by sync_parquet_to_databricks.sh
-- Catalog: mi2
-- Schema: i2l_syntheticmguh
-- Volume path: dbfs:/Volumes/mi2/i2l_syntheticmguh/raw/parquet

-- Create schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS mi2.i2l_syntheticmguh;

-- Create tables from Parquet files
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.allergies AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/allergies.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.careplans AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/careplans.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.claims AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/claims.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.claims_transactions AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/claims_transactions.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.codes AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/codes.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.conditions AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/conditions.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.devices AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/devices.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.encounters AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/encounters.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.imaging_studies AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/imaging_studies.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.immunizations AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/immunizations.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.medications AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/medications.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.observations AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/observations.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.organizations AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/organizations.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.patients AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/patients.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.payer_transitions AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/payer_transitions.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.payers AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/payers.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.procedures AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/procedures.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.providers AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/providers.parquet`;
CREATE OR REPLACE TABLE mi2.i2l_syntheticmguh.supplies AS SELECT * FROM parquet.`/Volumes/mi2/i2l_syntheticmguh/raw/parquet/supplies.parquet`;

-- Verify tables were created
SHOW TABLES IN mi2.i2l_syntheticmguh;

-- Show row counts for each table
SELECT 'allergies' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.allergies;
SELECT 'careplans' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.careplans;
SELECT 'claims' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.claims;
SELECT 'claims_transactions' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.claims_transactions;
SELECT 'codes' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.codes;
SELECT 'conditions' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.conditions;
SELECT 'devices' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.devices;
SELECT 'encounters' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.encounters;
SELECT 'imaging_studies' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.imaging_studies;
SELECT 'immunizations' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.immunizations;
SELECT 'medications' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.medications;
SELECT 'observations' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.observations;
SELECT 'organizations' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.organizations;
SELECT 'patients' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.patients;
SELECT 'payer_transitions' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.payer_transitions;
SELECT 'payers' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.payers;
SELECT 'procedures' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.procedures;
SELECT 'providers' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.providers;
SELECT 'supplies' as table_name, COUNT(*) as row_count FROM mi2.i2l_syntheticmguh.supplies;
